- job:
    name: ospurge-functional
    parent: devstack-tox-functional-consumer
    timeout: 3600
    required-projects:
      - openstack/devstack-gate
      - x/ospurge
      - openstack/designate
      - openstack/python-designateclient
    roles:
      - zuul: openstack-infra/devstack
    vars:
        devstack_plugins:
            designate: https://opendev.org/openstack/designate
        devstack_localrc:
            DESIGNATE_SERVICE_PORT_DNS: 5322
        tox_envlist: functional
    irrelevant-files: &dsvm-irrelevant-files
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^.git.*$
      - ^\.testr.conf$
      - ^LICENSE$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tox.ini$

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-cover-jobs
      - build-openstack-docs-pti
    check:
      jobs:
        - ospurge-functional
    gate:
      jobs:
        - ospurge-functional
